### ISSUE TITLE
Error: Max retries exceeded with url: /res.php

### ISSUE THREAD

**Issue by vladiscripts** [AndreiDrang/python-rucaptcha#16]
Из-за ошибки в модуле падают автономные скрипты его использующие, что критично. Падает с ошибкой `requests.exceptions.ConnectionError: HTTPConnectionPool(host='rucaptcha.com', port=80): Max retries exceeded with url: /res.php`

Алгоритм скрипта простой и последовательный: запрос к сайту для взятия капчи, сохранение её в файл (`captcha_file`), запрос на rucaptcha и получение ответа, отдача ответа на сайт (функция ниже).
`sleep_time` выставлен в `5`, согласно [документации api](https://rucaptcha.com/api-rucaptcha#limits). (Кстати, может стоит прописать 5 по умолчанию, это минимальное значение у них.)

И ещё хотелось бы, чтобы отдавался код этой ошибки. А то нет ни кода предупреждений от rucaptcha, и сама ошибка валится глобально по `requests.exceptions.ConnectionError`... И не понять чем именно превышен лимит.
Также не понятно, это бан аккаунта на 5-10 минут, или без бана?

Функция:
```
def send_captcha_for_solve(captcha_link=None, captcha_file=None):
    print('Sending captcha to the solve service')

    answer = ImageCaptcha.ImageCaptcha(rucaptcha_key=RUCAPTCHA_KEY, 
service_type='rucaptcha', sleep_time=5) \
        .captcha_handler(captcha_link=captcha_link, captcha_file=captcha_file)
    if answer['errorId'] == 0:
        print('text: %s, taskId: %s' % (answer['captchaSolve'], answer['taskId']))
        return answer
    elif answer['errorId'] == 1:
        print('errorId: %s, errorBody: %s' % (answer['errorId'], answer['errorBody']))
```

```
Loading captcha from site
Saving to captcha.jpg
Sending captcha to the solve service
Traceback (most recent call last):
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
(self.host, self.port), self.timeout, **extra_kw)
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
raise err
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
chunked=chunked)
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
conn.request(method, url, **httplib_request_kw)
File "C:\Users\Artem\Anaconda3\lib\http\client.py", line 1239, in request
self._send_request(method, url, body, headers, encode_chunked)
File "C:\Users\Artem\Anaconda3\lib\http\client.py", line 1285, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "C:\Users\Artem\Anaconda3\lib\http\client.py", line 1234, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "C:\Users\Artem\Anaconda3\lib\http\client.py", line 1026, in _send_output
self.send(msg)
File "C:\Users\Artem\Anaconda3\lib\http\client.py", line 964, in send
self.connect()
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\connection.py", line 166, in connect
conn = self._new_conn()
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000174B0744898>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Artem\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
timeout=timeout
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
_stacktrace=sys.exc_info()[2])
File "C:\Users\Artem\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='rucaptcha.com', port=80): Max retries exceeded with url: /res.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174B0744898>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "statuz03.py", line 316, in <module>
process_page(compId, wrong_ids)
File "statuz03.py", line 266, in process_page
process_page(compId, wrong_ids)
File "statuz03.py", line 254, in process_page
captchaAnswer = send_captcha_for_solve(captcha_file=captcha_path)
File "statuz03.py", line 38, in send_captcha_for_solve
.captcha_handler(captcha_link=captcha_link, captcha_file=captcha_file)
File "C:\Users\Artem\Anaconda3\lib\site-packages\python_rucaptcha\ImageCaptcha.py", line 207, in captcha_handler
captcha_response = requests.post(self.url_response, data=self.get_payload)
File "C:\Users\Artem\Anaconda3\lib\site-packages\requests\api.py", line 112, in post
return request('post', url, data=data, json=json, **kwargs)
File "C:\Users\Artem\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
return session.request(method=method, url=url, **kwargs)
File "C:\Users\Artem\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\Artem\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
r = adapter.send(request, **kwargs)
File "C:\Users\Artem\Anaconda3\lib\site-packages\requests\adapters.py", line 508, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='rucaptcha.com', port=80): Max retries exceeded with url: /res.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174B0744898>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
```

**Comment by vladiscripts** [comment]
Спасибо!
А теперь скрипт будет также падать, но с сообщением? Или продолжать долбится без выхода?
Просто сейчас мой скрипт запущен через батник run.bat, вроде:
```
:loop
python script.py
timeout /T 600
goto loop
```
Падая, он ждёт 10 минут (600 секунд) и перезапускается. Это просто работает. 

А если решать средствами этого обновления и питона, то надо в скрипт добавить
код, вроде:
```
import time
elif answer['errorId'] == 1:
    if "Блокировка на 10 минут" in answer['errorBody']:
         time.sleep(600)
    elif "Блокировка на 5 минут" in answer['errorBody']:
         time.sleep(300)
```
Так? Просто сам не могу поиграться со скриптом. Он работает удалённо, и ошибка сравнительно редкая (раз в несколько часов при запросах капчи по ~400 раз/час) чтобы запускать локально.

**Comment by AndreiDrang** [comment]
Он будет падать, но с сообщением, да.
По идее это должно реже происходить, т.к. добавил 5 попыток на переподключение, при неудаче.
Ну и да, твой код подходит под вариант решения.
Еще, я бы предложил написать небольшой кусок кода, на случай, если у тебя taskId есть, но тебя отрубило от сервера. Сейчас ты просто оставляешь ту капчу не решенной и отправляешь новую. Возможно имеет смысл взять taskId, подождать и попытаться по новой отправить запрос на решение.

**Comment by vladiscripts** [comment]
Да, у меня уже используется база для цикличной подгрузки списка необработанных запросов.

**Comment by vladiscripts** [comment]
А ещё можешь добавить, чтобы возвращался не только текст сообщения, но и код ошибки типа int? Вроде `if answer['errorId'] == 1001:`. 
Проще было бы обрабатывать результат. Сейчас какая ошибка надо выяснять, парся текстовую  строку ответа, что довольно необычно.

**Comment by AndreiDrang** [comment]
Дело в том, что номера есть лишь у некоторых ошибок, тогда либо надо вводить собственную нумерацию для всех ошибок, либо через raise Exception вызывать нужное исключение(но тогда не получится вернуть taskId).
Думаю стоит обдумать первый вариант.

**Comment by vladiscripts** [comment]
Открыл отдельную тему #17, ответили одновременно поэтому такая накладка.
